name: md-toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.20
  - scipy>=1.7
  - matplotlib>=3.3
  - mdanalysis>=2.0
  - scikit-learn>=1.0
  - pandas>=1.3
  - pyyaml>=5.4
  - tqdm>=4.62
  - seaborn>=0.11
  - jupyter
  - ipywidgets
  - pip
  - pip:
    - pyemma>=2.5